name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  check:
    strategy:
      matrix:
        os: [ubuntu-slim, windows-latest, macos-latest, ubuntu-24.04-arm]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6

      - uses: prefix-dev/setup-pixi@a0af7a228712d6121d37aba47adf55c1332c9c2e # v0.9.4
        with:
          pixi-version: v0.73.0
          run-install: false

      - name: Test
        run: pixi run check
        env:
          BUILD_EDITABLE_PYTHON: false

      - name: Upload Log
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: meson-log
          path: build/meson-logs/meson-log.txt
